// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7blkzN7-mevUWMb7LvGMU2b1PMpU59yg',
    appId: '1:660376214870:web:ab44359d9b637144a74af7',
    messagingSenderId: '660376214870',
    projectId: 'chat-app-af87f',
    authDomain: 'chat-app-af87f.firebaseapp.com',
    storageBucket: 'chat-app-af87f.appspot.com',
    measurementId: 'G-9BVV7CSXZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRrcMwoobxY4Q05Ef2efVsn_qD6uXjNw',
    appId: '1:660376214870:android:26a229044b06852ea74af7',
    messagingSenderId: '660376214870',
    projectId: 'chat-app-af87f',
    storageBucket: 'chat-app-af87f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA3SkBfo5AK-Cq7t4SaWmXkTv-pmXYt_E',
    appId: '1:660376214870:ios:341a48dfad3a767ca74af7',
    messagingSenderId: '660376214870',
    projectId: 'chat-app-af87f',
    storageBucket: 'chat-app-af87f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA3SkBfo5AK-Cq7t4SaWmXkTv-pmXYt_E',
    appId: '1:660376214870:ios:341a48dfad3a767ca74af7',
    messagingSenderId: '660376214870',
    projectId: 'chat-app-af87f',
    storageBucket: 'chat-app-af87f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7blkzN7-mevUWMb7LvGMU2b1PMpU59yg',
    appId: '1:660376214870:web:df8ab6fdfb257cd5a74af7',
    messagingSenderId: '660376214870',
    projectId: 'chat-app-af87f',
    authDomain: 'chat-app-af87f.firebaseapp.com',
    storageBucket: 'chat-app-af87f.appspot.com',
    measurementId: 'G-64507SYE5R',
  );
}
